-- 1. BASIC QUERIES AND DATA FILTERING

-- DISCONTINUED PRODUCT
SELECT ID, PRODUCT_NAME
FROM PRODUCTS
WHERE DISCONTINUED = 1;

-- 4 CHEAPEST PRODUCTS
SELECT PRODUCT_NAME, LIST_PRICE
FROM PRODUCTS
ORDER BY LIST_PRICE ASC
LIMIT 4;

-- PRODUCTS PRICED FROM 15 TO 25
SELECT PRODUCT_NAME, ID, LIST_PRICE
FROM PRODUCTS
WHERE LIST_PRICE BETWEEN 15 AND 25;

-- EMPLOYEE WITH ID AND FULL_NAME 
SELECT ID, CONCAT(FIRST_NAME, ' ', LAST_NAME) AS FULLNAME
FROM EMPLOYEES;

-- EMPLOYEES WHOSE NAMES START WITH 'A'
SELECT ID, FIRST_NAME, LAST_NAME
FROM EMPLOYEES
WHERE FIRST_NAME LIKE 'A%';

-- NUMBER OF DIFFERENT CITIES WHERE EMPLOYEES LIVE
SELECT COUNT(DISTINCT CITY) AS TOTALCITIES
FROM EMPLOYEES;

-- FIRST SHIPNAME FROM ORDERS
SELECT DISTINCT SHIP_NAME
FROM ORDERS;


-- 2. AGGREGATION AND SUBQUERIES

-- LOWEST AND HIGHEST PRICE
SELECT MIN(LIST_PRICE) AS MINPRICE,
       MAX(LIST_PRICE) AS MAXPRICE
FROM PRODUCTS;

-- NUMBER OF PRODUCTS IN SALE (DISCONTINUED = 0)
SELECT COUNT(*) AS ACTIVEPRODUCTS
FROM PRODUCTS
WHERE DISCONTINUED = 0;

-- THE AVERAGE AND STANDARD DEVIATION
SELECT AVG(LIST_PRICE) AS AVGPRICE,
       STDDEV_POP(LIST_PRICE) AS STDDEVPRICE
FROM PRODUCTS;

-- PRODUCTS WITH HIGHER THAN AVERAGE PRICES
SELECT PRODUCT_NAME, LIST_PRICE
FROM PRODUCTS
WHERE LIST_PRICE > (SELECT AVG(LIST_PRICE) FROM PRODUCTS);


-- 3. DATA MANIPULATION (DML)

-- ADD HABECO SUPPLIER
INSERT INTO SUPPLIERS(COMPANY, FIRST_NAME, LAST_NAME, CITY, COUNTRY_REGION)
VALUES ('HABECO', 'NGUYEN', 'HONG LINH', 'HANOI', 'VIETNAM');

-- ADD TBTRUC BACH PRODUCT
INSERT INTO PRODUCTS(PRODUCT_NAME, SUPPLIER_IDS, LIST_PRICE, DISCONTINUED, CATEGORY)
VALUES (
    'TBTRUC BACH',
    (SELECT ID FROM SUPPLIERS WHERE COMPANY = 'HABECO'),
    22,
    0,
    'BEVERAGES'
);

-- UPDATE PRICE FOR TRUC BACH 
UPDATE PRODUCTS
SET LIST_PRICE = 18
WHERE PRODUCT_NAME = 'TBTRUC BACH';

-- DELETE THE PRODUCT FIRST, AVOID ERROR FOREIGN KEY
DELETE FROM PRODUCTS
WHERE PRODUCT_NAME = 'TBTRUC BACH';

-- THEN DELETE THE SUPPLIER
DELETE FROM SUPPLIERS
WHERE COMPANY = 'HABECO';

